### PR TITLE
support additional authorization options at runtime

### PR DESCRIPTION
**Pull request by ashkulz**

### CODE REVIEW

**Comment by RettBehrens** [comment]
Hey @ashkulz apologies for the delayed response. Jenks is no longer at Xero and he had been the primary contributor until now. It looks like like there are some conflicts that need resolving before this can be merged - can you please update your PR accordingly? Additionally could you please submit a PR to the [sample app](https://github.com/XeroAPI/xero-oauth2-omniauth-sample) showing how an end user can leverage this functionality?

**Comment by ashkulz** [comment]
@RettBehrens resolved the merge conflicts. This implementation is pretty much the [same as in `omniauth-google-oauth2`](https://github.com/zquestz/omniauth-google-oauth2/blob/v1.1.1/lib/omniauth/strategies/google_oauth2.rb#L34-L38) -- we just need to pass in some `state` during our "Sign up with Xero" integration and get it back during the callback. I'm not sure how to really showcase it from the sample app -- any ideas?

**Comment by RettBehrens** [comment]
Hey @ashkulz apologies if I'm missing something. I'm new to this repo and omniauth.

In the sample app, using the current version of `omniauth-xero-oauth2`, I was able to pass a `state` param like so:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider(
    :xero_oauth2,
    ENV['CLIENT_ID'],
    ENV['CLIENT_SECRET'],
    scope: ENV['SCOPES'],
    state: 'sup3r$ecretSt@te'
  )
end
```

Resulting in this output:
```
Started POST "/auth/xero_oauth2" for ::1 at 2022-09-23 11:34:02 -0600
D, [2022-09-23T11:34:02.424791 #4300] DEBUG -- omniauth: (xero_oauth2) Request phase initiated.

Started GET "/auth/xero_oauth2/callback?code=Etynyl55JTecxQGWnkpdmKJxRJukUYHJERE_y2MtYbs&scope=openid%20profile%20email%20accounting.transactions%20accounting.budgets.read%20accounting.reports.read%20accounting.journals.read%20accounting.settings%20accounting.settings.read%20accounting.contacts%20accounting.contacts.read%20accounting.attachments%20accounting.attachments.read%20files%20files.read%20assets%20assets.read%20projects%20projects.read%20payroll.employees%20payroll.payruns%20payroll.payslip%20payroll.timesheets%20payroll.settings%20finance.accountingactivity.read%20finance.bankstatementsplus.read%20finance.cashvalidation.read%20finance.statements.read%20offline_access&state=sup3r$ecretSt@te&session_state=My3PZrCs_umCUZWf4P7RM9GVoKWv56G_vuFIHUe16QM.K-7i7XC6hErewpihTLlSEg" for ::1 at 2022-09-23 11:34:09 -0600
D, [2022-09-23T11:34:09.770953 #4300] DEBUG -- omniauth: (xero_oauth2)

Callback phase initiated.
OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".

Processing by SessionsController#create as HTML
Parameters:
{"code"=>"Etynyl55JTecxQGWnkpdmKJxRJukUYHJERE_y2MtYbs",
"scope"=>"openid profile email accounting.transactions accounting.budgets.read accounting.reports.read accounting.journals.read accounting.settings accounting.settings.read accounting.contacts accounting.contacts.read accounting.attachments accounting.attachments.read files files.read assets assets.read projects projects.read payroll.employees payroll.payruns payroll.payslip payroll.timesheets payroll.settings finance.accountingactivity.read finance.bankstatementsplus.read finance.cashvalidation.read finance.statements.read offline_access",
"state"=>"sup3r$ecretSt@te",
"session_state"=>"My3PZrCs_umCUZWf4P7RM9GVoKWv56G_vuFIHUe16QM.K-7i7XC6hErewpihTLlSEg",
"provider"=>"xero_oauth2"}
```

Is the issue that it's not present in the hash?
```
{"provider"=>:xero_oauth2,
 "uid"=>"redacted",
 "info"=>
  {"name"=>"Rett Behrens",
   "first_name"=>"Rett",
   "last_name"=>"Behrens",
   "email"=>"redacted"},
 "credentials"=>
  {"token"=>
    "redacted",
   "refresh_token"=>"redacted",
   "expires_at"=>1663956250,
   "expires"=>true},
 "extra"=>
  {"id_token"=>
    "redacted",
   "xero_tenants"=>
    [{"id"=>"redacted",
      "authEventId"=>"redacted",
      "tenantId"=>"redacted",
      "tenantType"=>"ORGANISATION",
      "tenantName"=>"Demo Company (AU)",
      "createdDateUtc"=>"2022-09-12T16:53:28.6998620",
      "updatedDateUtc"=>"2022-09-12T16:53:28.7018730"}],
   "raw_info"=>
    {"nbf"=>1663954450,
     "exp"=>1663954750,
     "iss"=>"https://identity.xero.com",
     "aud"=>"redacted",
     "iat"=>1663954450,
     "at_hash"=>"pFuVpTZdO9ZU3vVvyMRT_Q",
     "s_hash"=>"ghJzx4oQ--4UUq3vR9bNnw",
     "sid"=>"redacted",
     "sub"=>"redacted",
     "auth_time"=>1663954442,
     "xero_userid"=>"redacted",
     "global_session_id"=>"redacted",
     "preferred_username"=>"redacted",
     "email"=>"redacted",
     "given_name"=>"Rett",
     "family_name"=>"Behrens",
     "name"=>"Rett Behrens",
     "amr"=>["sso"]}}}
```

**Comment by ashkulz** [comment]
@RettBehrens, you're right that it works in that context -- but that's not useful for us as it'd be static. We're wanting to set the `state` dynamically at the time we do the authorization (_we store which domain we're currently on -- which is dynamic, as we're in 4 regions_) -- that's why we take it from `request.params` in the changed code. The same goes for the other parameters as well.

**Comment by RettBehrens** [comment]
@ashkulz Could you point me to a sample app that demonstrates what you're describing? I tried finding an example for the [Google](https://github.com/zquestz/omniauth-google-oauth2) implementation but couldn't

**Comment by ashkulz** [comment]
@RettBehrens if you apply this patch on the sample app, you'll see that with the current `master` it returns `sup3r$ecretSt@te` -- the values are those that are returned statically. The changes I made in this PR will make it return `runtime-sup3r$ecretSt@te` (i.e. picking it up at runtime).
```diff
diff --git a/app/views/home/index.html.erb b/app/views/home/index.html.erb
index 9de1674..e92add0 100644
--- a/app/views/home/index.html.erb
+++ b/app/views/home/index.html.erb
@@ -1,4 +1,5 @@
 <h4>Xero Ruby Oauth2 Demo App</h4>
 <p><%= form_tag('/auth/xero_oauth2', method: 'post') do %>
+  <input type="hidden" name="state" value="runtime-sup3r$ecretSt@te">
   <button type='submit'>Connect to Xero</button>
-<% end %></p>
\ No newline at end of file
+<% end %></p>
```

**Comment by RettBehrens** [comment]
@ashkulz I'm encountering `OmniAuth::Strategies::OAuth2::CallbackError` error: `CSRF detected`. This happens whether or not there is a state defined in the provider - I'm assuming this is because the runtime state will neither match the predefined state or lack there of.

**Comment by ashkulz** [comment]
Ah yes, we use `provider_ignores_state: true` in the configuration and add our own token in the (encrypted) runtime state we provide.

**Comment by RettBehrens** [comment]
Yep, ok. Was able to replicate locally and confirm these changes will work whether the state is provided at runtime or in the initializer config. Looks good to merge.

**Comment by ashkulz** [comment]
Thanks, @RettBehrens!

**Pull request merged**
